include:
  - remote: http://gitlab.shopzilla.com/terraform/pipeline-templates/-/raw/1.5_v1.8.0/template.gitlab-ci.yml
  
stages:
  - init
  - validate
  - build
  - deploy
  - cleanup

build:
  extends: .build

deploy:
 extends: .deploy
 dependencies:
   - build