include:
  - remote: http://gitlab.shopzilla.com/terraform/pipeline-templates/-/raw/master/latest_image_template.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy
  - cleanup

build:
  extends: .build

deploy:
 extends: .deploy
 dependencies:
   - build